import { DataSource } from 'typeorm';
import { MasterPermission } from '../entities';

export class MasterPermissionsSeed {
  constructor(private dataSource: DataSource) {}

  async run(): Promise<void> {
    const repository = this.dataSource.getRepository(MasterPermission);

    const permissions = [
      // Dashboard permissions
      {
        key: 'dashboard.view',
        name: 'View Dashboard',
        description: 'Access to dashboard overview',
        category: 'Dashboard',
        module: 'dashboard',
        action: 'view',
        defaultEnabled: true,
        sortOrder: 1,
      },
      {
        key: 'dashboard.analytics',
        name: 'View Analytics',
        description: 'Access to analytics and reports',
        category: 'Dashboard',
        module: 'dashboard',
        action: 'analytics',
        defaultEnabled: true,
        sortOrder: 2,
      },
      {
        key: 'dashboard.reports',
        name: 'Generate Reports',
        description: 'Generate and export reports',
        category: 'Dashboard',
        module: 'dashboard',
        action: 'reports',
        defaultEnabled: true,
        sortOrder: 3,
      },

      // Events permissions
      {
        key: 'events.read',
        name: 'View Events',
        description: 'View events and event details',
        category: 'Events',
        module: 'events',
        action: 'read',
        defaultEnabled: true,
        sortOrder: 1,
      },
      {
        key: 'events.create',
        name: 'Create Events',
        description: 'Create new events',
        category: 'Events',
        module: 'events',
        action: 'create',
        defaultEnabled: true,
        sortOrder: 2,
      },
      {
        key: 'events.update',
        name: 'Edit Events',
        description: 'Edit existing events',
        category: 'Events',
        module: 'events',
        action: 'update',
        defaultEnabled: true,
        sortOrder: 3,
      },
      {
        key: 'events.delete',
        name: 'Delete Events',
        description: 'Delete events',
        category: 'Events',
        module: 'events',
        action: 'delete',
        defaultEnabled: true,
        sortOrder: 4,
      },
      {
        key: 'events.publish',
        name: 'Publish Events',
        description: 'Publish and unpublish events',
        category: 'Events',
        module: 'events',
        action: 'publish',
        defaultEnabled: true,
        sortOrder: 5,
      },

      // Bookings permissions
      {
        key: 'bookings.read',
        name: 'View Bookings',
        description: 'View bookings and booking details',
        category: 'Bookings',
        module: 'bookings',
        action: 'read',
        defaultEnabled: true,
        sortOrder: 1,
      },
      {
        key: 'bookings.create',
        name: 'Create Bookings',
        description: 'Create new bookings',
        category: 'Bookings',
        module: 'bookings',
        action: 'create',
        defaultEnabled: true,
        sortOrder: 2,
      },
      {
        key: 'bookings.update',
        name: 'Edit Bookings',
        description: 'Edit existing bookings',
        category: 'Bookings',
        module: 'bookings',
        action: 'update',
        defaultEnabled: true,
        sortOrder: 3,
      },
      {
        key: 'bookings.cancel',
        name: 'Cancel Bookings',
        description: 'Cancel bookings',
        category: 'Bookings',
        module: 'bookings',
        action: 'cancel',
        defaultEnabled: true,
        sortOrder: 4,
      },
      {
        key: 'bookings.refund',
        name: 'Process Refunds',
        description: 'Process booking refunds',
        category: 'Bookings',
        module: 'bookings',
        action: 'refund',
        defaultEnabled: true,
        sortOrder: 5,
      },

      // Payment permissions
      {
        key: 'payments.read',
        name: 'View Payments',
        description: 'View payment details and transaction history',
        category: 'Payments',
        module: 'payments',
        action: 'read',
        defaultEnabled: true,
        sortOrder: 1,
      },
      {
        key: 'payments.create',
        name: 'Process Payments',
        description: 'Process new payments and transactions',
        category: 'Payments',
        module: 'payments',
        action: 'create',
        defaultEnabled: true,
        sortOrder: 2,
      },
      {
        key: 'payments.update',
        name: 'Update Payments',
        description: 'Update payment details and status',
        category: 'Payments',
        module: 'payments',
        action: 'update',
        defaultEnabled: true,
        sortOrder: 3,
      },
      {
        key: 'payments.refund',
        name: 'Process Refunds',
        description: 'Process payment refunds and chargebacks',
        category: 'Payments',
        module: 'payments',
        action: 'refund',
        defaultEnabled: true,
        sortOrder: 4,
      },
      {
        key: 'payments.plans',
        name: 'Manage Payment Plans',
        description: 'Create and manage payment plans and installments',
        category: 'Payments',
        module: 'payments',
        action: 'plans',
        defaultEnabled: true,
        sortOrder: 5,
      },

      // Inventory permissions
      {
        key: 'inventory.read',
        name: 'View Inventory',
        description: 'View inventory items and details',
        category: 'Inventory',
        module: 'inventory',
        action: 'read',
        defaultEnabled: true,
        sortOrder: 1,
      },
      {
        key: 'inventory.create',
        name: 'Create Inventory',
        description: 'Add new inventory items',
        category: 'Inventory',
        module: 'inventory',
        action: 'create',
        defaultEnabled: true,
        sortOrder: 2,
      },
      {
        key: 'inventory.update',
        name: 'Edit Inventory',
        description: 'Edit inventory items',
        category: 'Inventory',
        module: 'inventory',
        action: 'update',
        defaultEnabled: true,
        sortOrder: 3,
      },
      {
        key: 'inventory.delete',
        name: 'Delete Inventory',
        description: 'Remove inventory items',
        category: 'Inventory',
        module: 'inventory',
        action: 'delete',
        defaultEnabled: true,
        sortOrder: 4,
      },

      // Documents permissions
      {
        key: 'documents.read',
        name: 'View Documents',
        description: 'View and download documents',
        category: 'Documents',
        module: 'documents',
        action: 'read',
        defaultEnabled: true,
        sortOrder: 1,
      },
      {
        key: 'documents.create',
        name: 'Upload Documents',
        description: 'Upload new documents',
        category: 'Documents',
        module: 'documents',
        action: 'create',
        defaultEnabled: true,
        sortOrder: 2,
      },
      {
        key: 'documents.update',
        name: 'Edit Documents',
        description: 'Edit document metadata',
        category: 'Documents',
        module: 'documents',
        action: 'update',
        defaultEnabled: true,
        sortOrder: 3,
      },
      {
        key: 'documents.delete',
        name: 'Delete Documents',
        description: 'Remove documents',
        category: 'Documents',
        module: 'documents',
        action: 'delete',
        defaultEnabled: true,
        sortOrder: 4,
      },

      // Financial permissions
      {
        key: 'financial.read',
        name: 'View Financial Data',
        description: 'View revenue and financial reports',
        category: 'Financial',
        module: 'financial',
        action: 'read',
        defaultEnabled: true,
        sortOrder: 1,
      },
      {
        key: 'financial.transactions',
        name: 'View Transactions',
        description: 'View transaction history',
        category: 'Financial',
        module: 'financial',
        action: 'transactions',
        defaultEnabled: true,
        sortOrder: 2,
      },
      {
        key: 'financial.payouts',
        name: 'Manage Payouts',
        description: 'Process payouts and settlements',
        category: 'Financial',
        module: 'financial',
        action: 'payouts',
        defaultEnabled: true,
        sortOrder: 3,
      },

      // Users permissions
      {
        key: 'users.read',
        name: 'View Users',
        description: 'View user list and details',
        category: 'Users',
        module: 'users',
        action: 'read',
        defaultEnabled: true,
        sortOrder: 1,
      },
      {
        key: 'users.create',
        name: 'Create Users',
        description: 'Add new users to organization',
        category: 'Users',
        module: 'users',
        action: 'create',
        defaultEnabled: true,
        sortOrder: 2,
      },
      {
        key: 'users.update',
        name: 'Edit Users',
        description: 'Edit user details and roles',
        category: 'Users',
        module: 'users',
        action: 'update',
        defaultEnabled: true,
        sortOrder: 3,
      },
      {
        key: 'users.delete',
        name: 'Remove Users',
        description: 'Remove users from organization',
        category: 'Users',
        module: 'users',
        action: 'delete',
        defaultEnabled: true,
        sortOrder: 4,
      },

      // Settings permissions
      {
        key: 'settings.read',
        name: 'View Settings',
        description: 'View organization settings',
        category: 'Settings',
        module: 'settings',
        action: 'read',
        defaultEnabled: true,
        sortOrder: 1,
      },
      {
        key: 'settings.update',
        name: 'Update Settings',
        description: 'Update organization settings',
        category: 'Settings',
        module: 'settings',
        action: 'update',
        defaultEnabled: true,
        sortOrder: 2,
      },
      {
        key: 'settings.integrations',
        name: 'Manage Integrations',
        description: 'Configure third-party integrations',
        category: 'Settings',
        module: 'settings',
        action: 'integrations',
        defaultEnabled: true,
        sortOrder: 3,
      },
    ];

    // Use upsert to handle existing permissions
    for (const permission of permissions) {
      await repository.upsert(permission, ['key']);
    }

    console.log(`✅ Seeded ${permissions.length} master permissions`);
  }
}
