import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ConflictException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import { v4 as uuidv4 } from 'uuid';
import { ConfigService } from '@nestjs/config';

import { User, UserType } from '../../database/entities/user.entity';
import { Role } from '../../database/entities/role.entity';
import { CreateUserDto } from './dto/create-user.dto';
import { UpdateUserDto } from './dto/update-user.dto';
import { VerifyUserDto, ResendVerificationDto, VerifyByTokenDto } from './dto/verify-user.dto';
import { PaginationDto, PaginatedResponseDto } from '../../common/dto/pagination.dto';
import { FindUsersDto } from './dto/find-users.dto';
import { EmailService, UserVerificationData, UserCredentialsData } from '../email/email.service';
import { CryptoUtil } from '../../common/utils/crypto.util';

@Injectable()
export class UsersService {
  constructor(
    @InjectRepository(User)
    private userRepository: Repository<User>,
    @InjectRepository(Role)
    private roleRepository: Repository<Role>,
    private emailService: EmailService,
    private configService: ConfigService
  ) {}

  async create(createUserDto: CreateUserDto): Promise<User> {
    // Check if user already exists
    const existingUser = await this.findByEmail(createUserDto.email);
    if (existingUser) {
      throw new ConflictException('User with this email already exists');
    }

    // Get roles if provided
    let roles: Role[] = [];
    if (createUserDto.roleIds && createUserDto.roleIds.length > 0) {
      roles = await this.roleRepository.find({
        where: { id: In(createUserDto.roleIds) },
      });

      if (roles.length !== createUserDto.roleIds.length) {
        throw new BadRequestException('One or more roles not found');
      }

      // Check if any of the roles are system roles (only Product Admin can assign system roles)
      const systemRoles = roles.filter(role => role.isSystemRoleType());
      if (systemRoles.length > 0) {
        throw new BadRequestException(
          'Cannot assign system roles (Product Admin, Organization Admin) to users. These are static roles.'
        );
      }
    }

    // Organization admins can only create organization users (userType is set automatically to ORGANIZATION_USER)

    // Handle password generation
    let password = createUserDto.password;
    const isAutoGenerated = createUserDto.autoGenerateCredentials || !password;

    if (isAutoGenerated) {
      password = CryptoUtil.generateSecurePassword(12);
    }

    // Handle verification setup
    const requiresVerification = createUserDto.requiresVerification || false;
    let verificationToken: string | null = null;
    let verificationOtp: string | null = null;
    let verificationOtpExpires: Date | null = null;

    if (requiresVerification) {
      verificationToken = CryptoUtil.generateToken();
      verificationOtp = CryptoUtil.generateOTP();
      verificationOtpExpires = CryptoUtil.generateOTPExpiry(10); // 10 minutes
    }

    const user = this.userRepository.create({
      ...createUserDto,
      password,
      roles,
      isActive: !requiresVerification, // Inactive if verification required
      isVerified: !requiresVerification,
      requiresVerification,
      verificationToken,
      verificationOtp,
      verificationOtpExpires,
    });

    const savedUser = await this.userRepository.save(user);

    // Send emails based on configuration
    if (createUserDto.sendEmail || isAutoGenerated || requiresVerification) {
      await this.sendUserEmails(
        savedUser,
        password,
        requiresVerification,
        verificationToken,
        verificationOtp
      );
    }

    return savedUser;
  }

  async findAll(
    findUsersDto: FindUsersDto,
    currentUser?: User
  ): Promise<PaginatedResponseDto<User>> {
    const { page, limit, search, sortBy, sortOrder, role, status } = findUsersDto;

    const queryBuilder = this.userRepository
      .createQueryBuilder('user')
      .leftJoinAndSelect('user.roles', 'roles')
      .leftJoinAndSelect('roles.rolePermissions', 'rolePermissions');

    // Filter users based on current user's context
    if (currentUser) {
      if (currentUser.userType === UserType.ORGANIZATION_ADMIN) {
        // Organization admins can only see users in their organization
        queryBuilder.where('user.organizationId = :organizationId', {
          organizationId: currentUser.organizationId,
        });
      }
      // Product admins can see all users (no additional filter needed)
    }

    // Role filter
    if (role) {
      if (currentUser?.userType === UserType.ORGANIZATION_ADMIN) {
        queryBuilder.andWhere('user.userType = :role', { role });
      } else {
        queryBuilder.andWhere('user.userType = :role', { role });
      }
    }

    // Status filter
    if (status) {
      const isActive = status === 'active';
      if (currentUser?.userType === UserType.ORGANIZATION_ADMIN) {
        queryBuilder.andWhere('user.isActive = :isActive', { isActive });
      } else {
        queryBuilder.andWhere('user.isActive = :isActive', { isActive });
      }
    }

    // Search functionality
    if (search) {
      const searchCondition =
        '(user.firstName ILIKE :search OR user.lastName ILIKE :search OR user.email ILIKE :search)';
      if (currentUser?.userType === UserType.ORGANIZATION_ADMIN) {
        queryBuilder.andWhere(searchCondition, { search: `%${search}%` });
      } else {
        queryBuilder.andWhere(searchCondition, { search: `%${search}%` });
      }
    }

    // Sorting
    if (sortBy) {
      queryBuilder.orderBy(`user.${sortBy}`, sortOrder);
    } else {
      queryBuilder.orderBy('user.createdAt', 'DESC');
    }

    // Pagination
    queryBuilder.skip((page - 1) * limit).take(limit);

    const [users, total] = await queryBuilder.getManyAndCount();

    return new PaginatedResponseDto(users, total, page, limit);
  }

  async findByOrganization(
    organizationId: string,
    findUsersDto: FindUsersDto
  ): Promise<PaginatedResponseDto<User>> {
    const {
      page = 1,
      limit = 10,
      search,
      sortBy = 'firstName',
      sortOrder = 'ASC',
      role,
      status,
    } = findUsersDto;

    const queryBuilder = this.userRepository
      .createQueryBuilder('user')
      .leftJoinAndSelect('user.roles', 'roles')
      .leftJoinAndSelect('roles.rolePermissions', 'rolePermissions')
      .where('user.organizationId = :organizationId', { organizationId });

    // Role filter
    if (role) {
      queryBuilder.andWhere('user.userType = :role', { role });
    }

    // Status filter
    if (status) {
      const isActive = status === 'active';
      queryBuilder.andWhere('user.isActive = :isActive', { isActive });
    }

    // Search functionality
    if (search) {
      queryBuilder.andWhere(
        '(user.firstName ILIKE :search OR user.lastName ILIKE :search OR user.email ILIKE :search)',
        { search: `%${search}%` }
      );
    }

    // Sorting
    const validSortFields = ['firstName', 'lastName', 'email', 'createdAt', 'userType'];
    const sortField = validSortFields.includes(sortBy) ? sortBy : 'firstName';
    const order = sortOrder === 'DESC' ? 'DESC' : 'ASC';
    queryBuilder.orderBy(`user.${sortField}`, order);

    // Pagination
    queryBuilder.skip((page - 1) * limit).take(limit);

    const [users, total] = await queryBuilder.getManyAndCount();

    return new PaginatedResponseDto(users, total, page, limit);
  }

  async findById(id: string): Promise<User> {
    const user = await this.userRepository.findOne({
      where: { id },
      relations: ['roles', 'roles.rolePermissions'],
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    return user;
  }

  async findByEmail(email: string): Promise<User | null> {
    return this.userRepository.findOne({
      where: { email },
      relations: ['roles', 'roles.rolePermissions'],
    });
  }

  async update(id: string, updateUserDto: UpdateUserDto): Promise<User> {
    const user = await this.findById(id);

    // Check email uniqueness if email is being updated
    if (updateUserDto.email && updateUserDto.email !== user.email) {
      const existingUser = await this.findByEmail(updateUserDto.email);
      if (existingUser) {
        throw new ConflictException('User with this email already exists');
      }
    }

    // Update roles if provided
    if (updateUserDto.roleIds) {
      const roles = await this.roleRepository.find({
        where: { id: In(updateUserDto.roleIds) },
      });

      if (roles.length !== updateUserDto.roleIds.length) {
        throw new BadRequestException('One or more roles not found');
      }

      // Check if any of the roles are system roles (only Product Admin can assign system roles)
      const systemRoles = roles.filter(role => role.isSystemRoleType());
      if (systemRoles.length > 0) {
        throw new BadRequestException(
          'Cannot assign system roles (Product Admin, Organization Admin) to users. These are static roles.'
        );
      }

      user.roles = roles;
    }

    // Organization admins can only manage organization users (userType cannot be changed)

    // Update other fields
    Object.assign(user, updateUserDto);

    return this.userRepository.save(user);
  }

  async updatePassword(id: string, newPassword: string): Promise<void> {
    const user = await this.findById(id);
    user.password = newPassword;
    await this.userRepository.save(user);
  }

  async remove(id: string): Promise<void> {
    const user = await this.findById(id);

    // Soft delete by deactivating
    user.isActive = false;
    await this.userRepository.save(user);
  }

  async activate(id: string): Promise<User> {
    const user = await this.findById(id);
    user.isActive = true;
    return this.userRepository.save(user);
  }

  async deactivate(id: string): Promise<User> {
    const user = await this.findById(id);
    user.isActive = false;
    return this.userRepository.save(user);
  }

  async verifyUser(verifyUserDto: VerifyUserDto): Promise<User> {
    const user = await this.findById(verifyUserDto.userId);

    if (!user.requiresVerification) {
      throw new BadRequestException('User does not require verification');
    }

    if (user.isVerified) {
      throw new BadRequestException('User is already verified');
    }

    if (!user.verificationOtp || user.isVerificationExpired()) {
      throw new BadRequestException('Verification code has expired');
    }

    if (user.verificationOtp !== verifyUserDto.otp) {
      throw new BadRequestException('Invalid verification code');
    }

    // Verify the user
    user.isVerified = true;
    user.isActive = true;
    user.verificationOtp = null;
    user.verificationOtpExpires = null;
    user.verificationToken = null;

    return this.userRepository.save(user);
  }

  async verifyByToken(verifyByTokenDto: VerifyByTokenDto): Promise<User> {
    const user = await this.userRepository.findOne({
      where: { verificationToken: verifyByTokenDto.token },
    });

    if (!user) {
      throw new BadRequestException('Invalid verification token');
    }

    if (!user.requiresVerification) {
      throw new BadRequestException('User does not require verification');
    }

    if (user.isVerified) {
      throw new BadRequestException('User is already verified');
    }

    if (user.isVerificationExpired()) {
      throw new BadRequestException('Verification token has expired');
    }

    // If OTP is provided, verify it as well
    if (verifyByTokenDto.otp) {
      if (user.verificationOtp !== verifyByTokenDto.otp) {
        throw new BadRequestException('Invalid verification code');
      }
    }

    // Verify the user
    user.isVerified = true;
    user.isActive = true;
    user.verificationOtp = null;
    user.verificationOtpExpires = null;
    user.verificationToken = null;

    return this.userRepository.save(user);
  }

  async resendVerification(resendVerificationDto: ResendVerificationDto): Promise<void> {
    const user = await this.findById(resendVerificationDto.userId);

    if (!user.requiresVerification) {
      throw new BadRequestException('User does not require verification');
    }

    if (user.isVerified) {
      throw new BadRequestException('User is already verified');
    }

    // Generate new verification data
    const verificationToken = CryptoUtil.generateToken();
    const verificationOtp = CryptoUtil.generateOTP();
    const verificationOtpExpires = CryptoUtil.generateOTPExpiry(10);

    user.verificationToken = verificationToken;
    user.verificationOtp = verificationOtp;
    user.verificationOtpExpires = verificationOtpExpires;

    await this.userRepository.save(user);

    // Send verification email
    await this.sendVerificationEmail(user, verificationToken, verificationOtp);
  }

  private async sendUserEmails(
    user: User,
    password: string,
    requiresVerification: boolean,
    verificationToken?: string,
    verificationOtp?: string
  ): Promise<void> {
    const frontendUrl = this.configService.get('FRONTEND_URL', 'http://localhost:4200');
    const loginUrl = `${frontendUrl}/login`;

    if (requiresVerification && verificationToken && verificationOtp) {
      // Send verification email
      await this.sendVerificationEmail(user, verificationToken, verificationOtp);
    }

    // Send credentials email if password was auto-generated or sendEmail was requested
    const credentialsData: UserCredentialsData = {
      email: user.email,
      firstName: user.firstName,
      lastName: user.lastName,
      organizationName: undefined, // TODO: Get organization name if needed
      loginUrl,
      temporaryPassword: password,
      requiresVerification,
      verificationUrl:
        requiresVerification && verificationToken
          ? `${frontendUrl}/verify?token=${verificationToken}`
          : undefined,
      otp: requiresVerification ? verificationOtp : undefined,
    };

    await this.emailService.sendUserCredentials(credentialsData);
  }

  private async sendVerificationEmail(
    user: User,
    verificationToken: string,
    verificationOtp: string
  ): Promise<void> {
    const frontendUrl = this.configService.get('FRONTEND_URL', 'http://147.93.179.153:4201');
    const verificationUrl = `${frontendUrl}/verify-otp?token=${verificationToken}`;

    const verificationData: UserVerificationData = {
      email: user.email,
      firstName: user.firstName,
      lastName: user.lastName,
      organizationName: undefined, // TODO: Get organization name if needed
      verificationUrl,
      otp: verificationOtp,
      expiryMinutes: 10,
    };

    await this.emailService.sendUserVerification(verificationData);
  }

  private generateRandomPassword(): string {
    // Deprecated: Use CryptoUtil.generateSecurePassword instead
    return CryptoUtil.generateSecurePassword(12);
  }
}
