import { DataSource } from 'typeorm';
import { config } from 'dotenv';
import {
  User,
  Role,
  Permission,
  MasterPermission,
  Organization,
  OrganizationPermission,
  InventoryItem,
  InventoryCategory,
  Event,
  Booking,
  BookingInventoryAllocation,
  BookingExpense,
  BookingRevenue,
  Document,
  Payment,
  PaymentPlan,
  PaymentTransaction,
  RolePermission,
  FeaturePackage,
  OrganizationPackage,
  UserPermission,
} from './entities';

config();

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432'),
  username: process.env.DB_USERNAME || 'postgres',
  password: process.env.DB_PASSWORD || 'password',
  database: process.env.DB_NAME || 'event_booking',
  entities: [
    User,
    Role,
    Permission,
    MasterPermission,
    Organization,
    OrganizationPermission,
    InventoryItem,
    InventoryCategory,
    Event,
    Booking,
    BookingInventoryAllocation,
    BookingExpense,
    BookingRevenue,
    Document,
    Payment,
    PaymentPlan,
    PaymentTransaction,
    RolePermission,
    FeaturePackage,
    OrganizationPackage,
    UserPermission,
  ],
  migrations: [__dirname + '/migrations/*{.ts,.js}'],
  synchronize: true,
  logging: process.env.NODE_ENV === 'development',
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
});
